language: python

dist: xenial

cache: pip

matrix:
  include:
    - python: 3.7
      before_script:
      - >-
            [ -z "${TRAVIS_TAG}" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
            && openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
            || true
      - openssl aes-256-cbc -K $encrypted_16de86179301_key -iv $encrypted_16de86179301_iv -in .transit_env.enc -out .transit_env -d || true
      - openssl aes-256-cbc -K $encrypted_b4d7fa377f59_key -iv $encrypted_b4d7fa377f59_iv -in .dl_env.enc -out .dl_env -d || true

before_install:
  - npm install npm@latest -g
  - sudo apt-get update
  - sudo apt-get install pandoc
  - pip install pypandoc

install:
  - pip install tox-travis

script: tox
